// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { TouchEvent } from '../ludicrouslink/touch-event.js';


export enum ClientPayload {
  NONE = 0,
  TouchEvent = 1
}

export function unionToClientPayload(
  type: ClientPayload,
  accessor: (obj:TouchEvent) => TouchEvent|null
): TouchEvent|null {
  switch(ClientPayload[type]) {
    case 'NONE': return null; 
    case 'TouchEvent': return accessor(new TouchEvent())! as TouchEvent;
    default: return null;
  }
}

export function unionListToClientPayload(
  type: ClientPayload, 
  accessor: (index: number, obj:TouchEvent) => TouchEvent|null, 
  index: number
): TouchEvent|null {
  switch(ClientPayload[type]) {
    case 'NONE': return null; 
    case 'TouchEvent': return accessor(index, new TouchEvent())! as TouchEvent;
    default: return null;
  }
}
