// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CodecInfo } from '../hstreamer/codec-info.js';
import { VideoFrame } from '../hstreamer/video-frame.js';


export enum ServerPayload {
  NONE = 0,
  CodecInfo = 1,
  VideoFrame = 2
}

export function unionToServerPayload(
  type: ServerPayload,
  accessor: (obj:CodecInfo|VideoFrame) => CodecInfo|VideoFrame|null
): CodecInfo|VideoFrame|null {
  switch(ServerPayload[type]) {
    case 'NONE': return null; 
    case 'CodecInfo': return accessor(new CodecInfo())! as CodecInfo;
    case 'VideoFrame': return accessor(new VideoFrame())! as VideoFrame;
    default: return null;
  }
}

export function unionListToServerPayload(
  type: ServerPayload, 
  accessor: (index: number, obj:CodecInfo|VideoFrame) => CodecInfo|VideoFrame|null, 
  index: number
): CodecInfo|VideoFrame|null {
  switch(ServerPayload[type]) {
    case 'NONE': return null; 
    case 'CodecInfo': return accessor(index, new CodecInfo())! as CodecInfo;
    case 'VideoFrame': return accessor(index, new VideoFrame())! as VideoFrame;
    default: return null;
  }
}
