// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TouchAction {
  Down = 0,
  Move = 1,
  Up = 2,
  Cancel = 3
}
