// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TouchAction } from '../ludicrouslink/touch-action.js';


export class TouchEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TouchEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTouchEvent(bb:flatbuffers.ByteBuffer, obj?:TouchEvent):TouchEvent {
  return (obj || new TouchEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTouchEvent(bb:flatbuffers.ByteBuffer, obj?:TouchEvent):TouchEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TouchEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

action():TouchAction {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : TouchAction.Down;
}

pointerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

pressure():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startTouchEvent(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addAction(builder:flatbuffers.Builder, action:TouchAction) {
  builder.addFieldInt8(0, action, TouchAction.Down);
}

static addPointerId(builder:flatbuffers.Builder, pointerId:number) {
  builder.addFieldInt8(1, pointerId, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(2, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(3, y, 0.0);
}

static addPressure(builder:flatbuffers.Builder, pressure:number) {
  builder.addFieldFloat32(4, pressure, 0.0);
}

static endTouchEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTouchEvent(builder:flatbuffers.Builder, action:TouchAction, pointerId:number, x:number, y:number, pressure:number):flatbuffers.Offset {
  TouchEvent.startTouchEvent(builder);
  TouchEvent.addAction(builder, action);
  TouchEvent.addPointerId(builder, pointerId);
  TouchEvent.addX(builder, x);
  TouchEvent.addY(builder, y);
  TouchEvent.addPressure(builder, pressure);
  return TouchEvent.endTouchEvent(builder);
}
}
