// automatically generated by the FlatBuffers compiler, do not modify

package hstreamer

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class CodecInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CodecInfo {
        __init(_i, _bb)
        return this
    }
    fun sps(j: Int) : UByte {
        val o = __offset(4)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val spsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val spsAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun spsInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    fun pps(j: Int) : UByte {
        val o = __offset(6)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val ppsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val ppsAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun ppsInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsCodecInfo(_bb: ByteBuffer): CodecInfo = getRootAsCodecInfo(_bb, CodecInfo())
        fun getRootAsCodecInfo(_bb: ByteBuffer, obj: CodecInfo): CodecInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCodecInfo(builder: FlatBufferBuilder, spsOffset: Int, ppsOffset: Int) : Int {
            builder.startTable(2)
            addPps(builder, ppsOffset)
            addSps(builder, spsOffset)
            return endCodecInfo(builder)
        }
        fun startCodecInfo(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addSps(builder: FlatBufferBuilder, sps: Int) = builder.addOffset(0, sps, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createSpsVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startSpsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addPps(builder: FlatBufferBuilder, pps: Int) = builder.addOffset(1, pps, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createPpsVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startPpsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun endCodecInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
