// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hstreamer

import "strconv"

type ClientPayload byte

const (
	ClientPayloadNONE       ClientPayload = 0
	ClientPayloadTouchEvent ClientPayload = 1
)

var EnumNamesClientPayload = map[ClientPayload]string{
	ClientPayloadNONE:       "NONE",
	ClientPayloadTouchEvent: "TouchEvent",
}

var EnumValuesClientPayload = map[string]ClientPayload{
	"NONE":       ClientPayloadNONE,
	"TouchEvent": ClientPayloadTouchEvent,
}

func (v ClientPayload) String() string {
	if s, ok := EnumNamesClientPayload[v]; ok {
		return s
	}
	return "ClientPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
