// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ludicrouslink

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsClientMessage(buf []byte, offset flatbuffers.UOffsetT) *ClientMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientMessage(buf []byte, offset flatbuffers.UOffsetT) *ClientMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientMessage) PayloadType() ClientPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ClientPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientMessage) MutatePayloadType(n ClientPayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ClientMessage) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ClientMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ClientMessageAddPayloadType(builder *flatbuffers.Builder, payloadType ClientPayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func ClientMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func ClientMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
