// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hstreamer

import "strconv"

type ServerPayload byte

const (
	ServerPayloadNONE       ServerPayload = 0
	ServerPayloadCodecInfo  ServerPayload = 1
	ServerPayloadVideoFrame ServerPayload = 2
)

var EnumNamesServerPayload = map[ServerPayload]string{
	ServerPayloadNONE:       "NONE",
	ServerPayloadCodecInfo:  "CodecInfo",
	ServerPayloadVideoFrame: "VideoFrame",
}

var EnumValuesServerPayload = map[string]ServerPayload{
	"NONE":       ServerPayloadNONE,
	"CodecInfo":  ServerPayloadCodecInfo,
	"VideoFrame": ServerPayloadVideoFrame,
}

func (v ServerPayload) String() string {
	if s, ok := EnumNamesServerPayload[v]; ok {
		return s
	}
	return "ServerPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
