// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ludicrouslink

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServerMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsServerMessage(buf []byte, offset flatbuffers.UOffsetT) *ServerMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServerMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishServerMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsServerMessage(buf []byte, offset flatbuffers.UOffsetT) *ServerMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServerMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedServerMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ServerMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServerMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServerMessage) PayloadType() ServerPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ServerPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ServerMessage) MutatePayloadType(n ServerPayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ServerMessage) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ServerMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ServerMessageAddPayloadType(builder *flatbuffers.Builder, payloadType ServerPayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func ServerMessageAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func ServerMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
