// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hstreamer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TouchEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsTouchEvent(buf []byte, offset flatbuffers.UOffsetT) *TouchEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TouchEvent{}
	x.Init(buf, n+offset)
	return x
}

func FinishTouchEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTouchEvent(buf []byte, offset flatbuffers.UOffsetT) *TouchEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TouchEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTouchEventBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TouchEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TouchEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TouchEvent) Action() TouchAction {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TouchAction(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TouchEvent) MutateAction(n TouchAction) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *TouchEvent) PointerId() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TouchEvent) MutatePointerId(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *TouchEvent) X() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TouchEvent) MutateX(n float32) bool {
	return rcv._tab.MutateFloat32Slot(8, n)
}

func (rcv *TouchEvent) Y() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TouchEvent) MutateY(n float32) bool {
	return rcv._tab.MutateFloat32Slot(10, n)
}

func (rcv *TouchEvent) Pressure() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *TouchEvent) MutatePressure(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func TouchEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func TouchEventAddAction(builder *flatbuffers.Builder, action TouchAction) {
	builder.PrependInt8Slot(0, int8(action), 0)
}
func TouchEventAddPointerId(builder *flatbuffers.Builder, pointerId byte) {
	builder.PrependByteSlot(1, pointerId, 0)
}
func TouchEventAddX(builder *flatbuffers.Builder, x float32) {
	builder.PrependFloat32Slot(2, x, 0.0)
}
func TouchEventAddY(builder *flatbuffers.Builder, y float32) {
	builder.PrependFloat32Slot(3, y, 0.0)
}
func TouchEventAddPressure(builder *flatbuffers.Builder, pressure float32) {
	builder.PrependFloat32Slot(4, pressure, 0.0)
}
func TouchEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
