// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ludicrouslink

import "strconv"

type TouchAction int8

const (
	TouchActionDown   TouchAction = 0
	TouchActionMove   TouchAction = 1
	TouchActionUp     TouchAction = 2
	TouchActionCancel TouchAction = 3
)

var EnumNamesTouchAction = map[TouchAction]string{
	TouchActionDown:   "Down",
	TouchActionMove:   "Move",
	TouchActionUp:     "Up",
	TouchActionCancel: "Cancel",
}

var EnumValuesTouchAction = map[string]TouchAction{
	"Down":   TouchActionDown,
	"Move":   TouchActionMove,
	"Up":     TouchActionUp,
	"Cancel": TouchActionCancel,
}

func (v TouchAction) String() string {
	if s, ok := EnumNamesTouchAction[v]; ok {
		return s
	}
	return "TouchAction(" + strconv.FormatInt(int64(v), 10) + ")"
}
