// automatically generated by the FlatBuffers compiler, do not modify

package hstreamer

@Suppress("unused")
class ClientPayload private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val TouchEvent: UByte = 1u
    }
}
