// automatically generated by the FlatBuffers compiler, do not modify

package hstreamer

@Suppress("unused")
class ServerPayload private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val CodecInfo: UByte = 1u
        const val VideoFrame: UByte = 2u
    }
}
