// automatically generated by the FlatBuffers compiler, do not modify

package ludicrouslink

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TouchEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TouchEvent {
        __init(_i, _bb)
        return this
    }
    val action : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val pointerId : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val x : Float
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val y : Float
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val pressure : Float
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTouchEvent(_bb: ByteBuffer): TouchEvent = getRootAsTouchEvent(_bb, TouchEvent())
        fun getRootAsTouchEvent(_bb: ByteBuffer, obj: TouchEvent): TouchEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTouchEvent(builder: FlatBufferBuilder, action: Byte, pointerId: UByte, x: Float, y: Float, pressure: Float) : Int {
            builder.startTable(5)
            addPressure(builder, pressure)
            addY(builder, y)
            addX(builder, x)
            addPointerId(builder, pointerId)
            addAction(builder, action)
            return endTouchEvent(builder)
        }
        fun startTouchEvent(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addAction(builder: FlatBufferBuilder, action: Byte) = builder.addByte(0, action, 0)
        fun addPointerId(builder: FlatBufferBuilder, pointerId: UByte) = builder.addByte(1, pointerId.toByte(), 0)
        fun addX(builder: FlatBufferBuilder, x: Float) = builder.addFloat(2, x, 0.0)
        fun addY(builder: FlatBufferBuilder, y: Float) = builder.addFloat(3, y, 0.0)
        fun addPressure(builder: FlatBufferBuilder, pressure: Float) = builder.addFloat(4, pressure, 0.0)
        fun endTouchEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
