// automatically generated by the FlatBuffers compiler, do not modify

package hstreamer

@Suppress("unused")
class TouchAction private constructor() {
    companion object {
        const val Down: Byte = 0
        const val Move: Byte = 1
        const val Up: Byte = 2
        const val Cancel: Byte = 3
    }
}
