// automatically generated by the FlatBuffers compiler, do not modify

package ludicrouslink

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class VideoFrame : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : VideoFrame {
        __init(_i, _bb)
        return this
    }
    fun data(j: Int) : UByte {
        val o = __offset(4)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val dataLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val dataAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun dataInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val keyFrame : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val timestamp : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsVideoFrame(_bb: ByteBuffer): VideoFrame = getRootAsVideoFrame(_bb, VideoFrame())
        fun getRootAsVideoFrame(_bb: ByteBuffer, obj: VideoFrame): VideoFrame {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createVideoFrame(builder: FlatBufferBuilder, dataOffset: Int, keyFrame: Boolean, timestamp: ULong) : Int {
            builder.startTable(3)
            addTimestamp(builder, timestamp)
            addData(builder, dataOffset)
            addKeyFrame(builder, keyFrame)
            return endVideoFrame(builder)
        }
        fun startVideoFrame(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(0, data, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createDataVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startDataVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun addKeyFrame(builder: FlatBufferBuilder, keyFrame: Boolean) = builder.addBoolean(1, keyFrame, false)
        fun addTimestamp(builder: FlatBufferBuilder, timestamp: ULong) = builder.addLong(2, timestamp.toLong(), 0)
        fun endVideoFrame(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
