// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hstreamer

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type VideoFrame struct {
	_tab flatbuffers.Table
}

func GetRootAsVideoFrame(buf []byte, offset flatbuffers.UOffsetT) *VideoFrame {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &VideoFrame{}
	x.Init(buf, n+offset)
	return x
}

func FinishVideoFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVideoFrame(buf []byte, offset flatbuffers.UOffsetT) *VideoFrame {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &VideoFrame{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVideoFrameBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *VideoFrame) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *VideoFrame) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *VideoFrame) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *VideoFrame) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *VideoFrame) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *VideoFrame) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *VideoFrame) KeyFrame() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *VideoFrame) MutateKeyFrame(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *VideoFrame) Timestamp() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *VideoFrame) MutateTimestamp(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func VideoFrameStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func VideoFrameAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func VideoFrameStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func VideoFrameAddKeyFrame(builder *flatbuffers.Builder, keyFrame bool) {
	builder.PrependBoolSlot(1, keyFrame, false)
}
func VideoFrameAddTimestamp(builder *flatbuffers.Builder, timestamp uint64) {
	builder.PrependUint64Slot(2, timestamp, 0)
}
func VideoFrameEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
